# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Release artifactbundle

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'patch | minor | major'
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: swiftty/swiftpm-artifactbundle-builder@v1
      with:
        swift-version: '5.7'
        depth: 1

  release:
    needs: [ build ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swiftty/nextversion@v0.0.1
      id: nextversion
      with:
        bump: ${{ github.event.inputs.version }}
    - name: git settings
      run: |
        # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: swiftty/swiftpm-artifactbundle-bundler@v1
      id: bundler
      with:
        variants-version: ${{ steps.nextversion.outputs.next  }}
    - name: update README
      run: |
        CHECKSUM=echo "${{ steps.bundler.outputs.checksums }}" | cut -f 1 -d " "

        sed -i -E 's/download\/(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)/download\/${{ steps.nextversion.outputs.next }}/g' README.md
        sed -i -E "s/checksum: \"[a-z0-9]+\"/checksum: \"$CHECKSUM\"/g" README.md

        git add README.md
        git commit -m 'update README.md'
        git push origin main
    - uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        tag_name: ${{ steps.nextversion.outputs.next }}
        body: | 
          ## Checksums

          - for `.binaryTarget(name:url:checksum:)`

            ```
            ${{ steps.bundler.outputs.checksums }}
            ```

          ---
        files: |
          ${{ steps.bundler.outputs.path }}/**
